# Generated by Django 3.0.14 on 2022-09-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_discount_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='discount',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id пользователя'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='payment.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='id пользователя'),
        ),
    ]
