# Generated by Django 3.0.14 on 2022-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220928_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=5, verbose_name='Налог'),
        ),
    ]
