# Generated by Django 3.0.14 on 2022-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20220928_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Налог'),
        ),
    ]
